name: Update next DSC meeting date

on:
  schedule:
    # run every tuesday at 0:00 UTC
    # posix cron syntax: minute, hour, day of the month, month, weekday
    - cron: "0 0 * * 4"
  workflow_dispatch:

jobs:
  update-next-dsc-meeting:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The data is calling!"
      - run: echo "The job was automatically triggered by a ${{ github.event_namme }} event."
      - name: checkout
        uses: actions/checkout@v4
      - run: echo "The ${{ github.repository }} has been cloned to the runner."
      - name: update
        run: |
          date -d "next wednesday" +%x > _includes/next-dsc-meeting.txt
          git config --global user.name "Robo-Bjarne"
          git config --global user.email "robo-bjarne@users.noreply.github.com"
          git commit -am "update next-dsc-meeting.txt"
          git push
      - run: echo "Until we meet again."
